In [35]:
import numpy as np
A = np.arange(1,7)
A.reshape(2,3)



array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
C = np.arange(1,26).reshape(5,5)
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
C[0,2] = -3
C

array([[ 1,  2, -3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
C[2,3] = -14
C

array([[  1,   2,  -3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [18]:
C[3] = [-16,-17,-18,-19,-20]
C

array([[  1,   2,  -3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [-16, -17, -18, -19, -20],
       [ 21,  22,  23,  24,  25]])

In [19]:
C[-1]

array([21, 22, 23, 24, 25])

In [20]:
# Slicing syntax is [start:stop]
# Striding syntax is [ start:strop:step]
C

array([[  1,   2,  -3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [-16, -17, -18, -19, -20],
       [ 21,  22,  23,  24,  25]])

In [23]:
C[1,1:3]

array([7, 8])

In [31]:
C[0:4,1]
C

array([[  1,   2,  -3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [-16, -17, -18, -19, -20],
       [ 21,  22,  23,  24,  25]])

In [33]:
C [0:4,0]

array([  1,   6,  11, -16])

Now from here is slicing in numpy

In [47]:
a = np.arange(10)
print(a[2:-2:2])

[2 4 6]


In [40]:
a= np.arange(10)
b= a[5]
b

5

In [87]:
a = np.array([[[1,2,3,5],[6,7,8,9]],[[33,22,44,55],[0,0,0,0]]])
for x in a:
     print("x represents the 2 D array")
     print(x)



x represents the 2 D array
[[1 2 3 5]
 [6 7 8 9]]
x represents the 2 D array
[[33 22 44 55]
 [ 0  0  0  0]]


In [77]:
x= np.array([[[1,2,3,4],[1,2,2,2],[4,4,4,4]]])
for a in x:
    print("x represtns in 2 d")
    print(x)

x represtns in 2 d
[[[1 2 3 4]
  [1 2 2 2]
  [4 4 4 4]]]


In [83]:
x = np.array([[[1,2,3,4],[4,4,4,4]],[[5,5,5,5],[2,2,2,2]]])
print(x)

[[[1 2 3 4]
  [4 4 4 4]]

 [[5 5 5 5]
  [2 2 2 2]]]


In [85]:
a = np.arange(6).reshape(2,3)
for x in a:
     print(x,end=" ")

[0 1 2] [3 4 5] 