In [65]:
import numpy as np
a1 = np.array([11,12,13,14])
print(a1)
a1.shape

[11 12 13 14]


(4,)

In [22]:
a1.ndim


1

In [68]:
z = np.arange(5)
print(z)
z.shape



[0 1 2 3 4]


(5,)

In [89]:
"""Two Dimensional Arrays"""
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
ar.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [90]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
c=arr*ar

c

[[1 2 3 4]
 [5 6 7 8]]


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [73]:
c.shape

(2, 4)

In [77]:
arr = np.arange(1,9)
print(arr)

[1 2 3 4 5 6 7 8]


In [79]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
arr.reshape(4,2)
print(ar)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
ar.shape=(4,2)
print(ar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
ar.shape

(4, 2)

In [32]:
a3 = np.array([[1,2,3,'a string'],[4,5,6,'a book']])
print(a3)

[['1' '2' '3' 'a string']
 ['4' '5' '6' 'a book']]


In [82]:
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
print(a1)

[1 2 3 4]


In [41]:
a1 *2

array([2, 4, 6, 8])

In [42]:
a1 +2 

array([3, 4, 5, 6])

In [43]:
print(a1)

[1 2 3 4]


In [83]:
a1 = a1+2

In [84]:
print(a1)

[13 14 15 16]


In [85]:
print(a1)

[13 14 15 16]


In [86]:

a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(a1+a2)

[ 6  8 10 12]


In [87]:
a1*a2

array([ 5, 12, 21, 32])